theme: minima
title: ğŸ’¼ Portafolio de Santiago Figueroa Rodriguez
description: ğŸ§‘â€ğŸ’»En este espacio comparto proyectos e ideas en las que eh trabajado.
author: SantiagoFigueroaR linkedin: https://www.google.com/search?q=https://www.linkedin.com/in/santiago-figueroa-rodriguez/

